import { existsSync, readFileSync } from "node:fs";
import path from "node:path";
import type { DependentProfile, StaffProfile } from "../types/triage.js";

/**
 * Oracle Fusion HCM simulation adapter (see docs/oracle-fusion-hcm-integration.md
 * for the full integration plan). This is still simulation-only - it reads a
 * locally-generated Oracle-Fusion-HCM-shaped JSON fixture, not a live Oracle
 * REST connection - but it deliberately mirrors the real adapter's runtime
 * flow and field names so a future live Oracle HTTP client can be dropped in
 * behind the same `resolveStaffProfile()` contract without changing anything
 * that reads `StaffProfile` (src/routes/staff.ts, src/routes/triage.ts, etc.).
 *
 * Data source: data/generated/ist_qatar_seed_data.json's `oracle_fusion_hcm_api`
 * section (26,000 synthetic employees), generated by
 * python/generate_synthetic_pdp_data.py, in the exact REST collection shape
 * documented in the integration plan (`publicWorkers`, `workers`,
 * `workRelationships`, `assignments`, `hcmContacts`, `contactRelationships`,
 * `absences`) with genuine Oracle field names (PersonId, PersonNumber,
 * workersUniqID, AssignmentStatusType, etc.) - not an ad-hoc flat mock shape.
 */

const ORACLE_SEED_DATA_PATH = path.resolve(process.cwd(), "data", "generated", "ist_qatar_seed_data.json");

type OracleLink = { rel: string; href: string; name: string; kind: string };

type OraclePublicWorker = {
  PersonId: number;
  PersonNumber: string;
  DisplayName: string;
  WorkerType: string;
  AssignmentNumber: string;
  AssignmentStatusType: string;
  DepartmentName: string;
  JobName: string;
  LocationName: string;
  links: OracleLink[];
};

type OracleWorker = {
  workersUniqID: string;
  PersonId: number;
  PersonNumber: string;
  DisplayName: string;
  DateOfBirth: string;
  Gender: string;
  WorkerType: string;
  CorrespondenceLanguage: string;
  LegislationCode: string;
  links: OracleLink[];
};

type OracleAssignment = {
  workersUniqID: string;
  PeriodOfServiceId: string;
  AssignmentId: string;
  AssignmentNumber: string;
  PersonId: number;
  PersonNumber: string;
  AssignmentStatusType: string;
  BusinessUnitName: string;
  DepartmentName: string;
  JobName: string;
  LocationName: string;
  PrimaryAssignmentFlag: boolean;
  EffectiveStartDate: string;
};

type OracleAbsence = {
  AbsenceEntryId: string;
  PersonId: number;
  PersonNumber: string;
  AbsenceType: string;
  ApprovalStatusCd: string;
  StartDate: string;
  EndDate: string;
};

type OracleHcmContact = {
  hcmContactsUniqID: string;
  ContactPersonId: number;
  ContactPersonNumber: string;
  DisplayName: string;
  DateOfBirth: string;
  Gender: string;
  LegislationCode: string;
  links: OracleLink[];
};

type OracleContactRelationship = {
  ContactRelationshipId: string;
  PersonId: number;
  PersonNumber: string;
  ContactPersonId: number;
  ContactPersonNumber: string;
  RelationshipType: string;
  EmergencyContactFlag: boolean;
  DependentFlag: boolean;
  StartDate: string;
  /** Only set for the legacy demo profiles - preserves their historical
   *  dependent ID strings (referenced by existing tests/fixtures) instead of
   *  deriving one from ContactRelationshipId. */
  legacyDependentId?: string;
};

type OracleCollection<T> = { resource: string; count: number; hasMore: boolean; items: T[] };

type OracleSeedFile = {
  oracle_fusion_hcm_api: {
    collections: {
      publicWorkers: OracleCollection<OraclePublicWorker>;
      workers: OracleCollection<OracleWorker>;
      assignments: OracleCollection<OracleAssignment>;
      absences: OracleCollection<OracleAbsence>;
      hcmContacts: OracleCollection<OracleHcmContact>;
      contactRelationships: OracleCollection<OracleContactRelationship>;
    };
  };
};

type OracleIndex = {
  publicWorkerByPersonNumber: Map<string, OraclePublicWorker>;
  workerByPersonId: Map<number, OracleWorker>;
  assignmentByPersonId: Map<number, OracleAssignment>;
  absencesByPersonId: Map<number, OracleAbsence[]>;
  contactsByContactPersonId: Map<number, OracleHcmContact>;
  relationshipsByPersonId: Map<number, OracleContactRelationship[]>;
};

let cachedIndex: OracleIndex | undefined;

/**
 * A handful of well-known demo staff IDs used throughout existing tests and
 * the demo login flow (predates this adapter). Represented here as
 * Oracle-shaped records injected into the same index at load time, rather
 * than as a separate legacy code path - they go through the exact same
 * normalization pipeline as the other 26,000 synthetic employees.
 */
const LEGACY_DEMO_WORKERS: Array<{
  personId: number;
  personNumber: string;
  displayName: string;
  department: string;
  jobTitle: string;
  assignmentStatus: string;
  dateOfBirthIso: string;
  biologicalSex: "male" | "female";
  dependents: Array<{ id: string; relationshipType: string; age: number; dateOfBirthIso: string; biologicalSex: "male" | "female" }>;
}> = [
  {
    personId: 800000000001,
    personNumber: "IST-1001",
    displayName: "Synthetic Pilot IST-1001",
    department: "Flight Operations",
    jobTitle: "Pilot",
    assignmentStatus: "ACTIVE",
    dateOfBirthIso: "1991-03-15",
    biologicalSex: "male",
    dependents: [
      { id: "dep_ist_1001_child_01", relationshipType: "DAUGHTER", age: 6, dateOfBirthIso: "2020-04-02", biologicalSex: "female" },
      { id: "dep_ist_1001_child_02", relationshipType: "SON", age: 3, dateOfBirthIso: "2023-02-12", biologicalSex: "male" }
    ]
  },
  {
    personId: 800000000002,
    personNumber: "IST-10001",
    displayName: "Synthetic Cabin Crew IST-10001",
    department: "Flight Operations",
    jobTitle: "Cabin Crew",
    assignmentStatus: "ACTIVE",
    dateOfBirthIso: "1994-05-20",
    biologicalSex: "female",
    dependents: [{ id: "dep_demo_10001_child", relationshipType: "DAUGHTER", age: 8, dateOfBirthIso: "2018-01-10", biologicalSex: "female" }]
  },
  {
    personId: 800000000003,
    personNumber: "IST-2002",
    displayName: "Synthetic Cabin Crew IST-2002",
    department: "Cabin Services",
    jobTitle: "Cabin Crew",
    assignmentStatus: "ACTIVE",
    dateOfBirthIso: "1985-09-08",
    biologicalSex: "female",
    dependents: []
  },
  {
    personId: 800000000004,
    personNumber: "IST-20002",
    displayName: "Synthetic Ramp Supervisor IST-20002",
    department: "Ground Services",
    jobTitle: "Ramp Supervisor",
    assignmentStatus: "LEAVE_OF_ABSENCE",
    dateOfBirthIso: "1979-11-18",
    biologicalSex: "male",
    dependents: []
  },
  {
    personId: 800000000005,
    personNumber: "IST-3003",
    displayName: "Synthetic Operations Specialist IST-3003",
    department: "Airport Operations",
    jobTitle: "Operations Specialist",
    assignmentStatus: "ACTIVE",
    dateOfBirthIso: "1997-06-21",
    biologicalSex: "male",
    dependents: []
  },
  {
    personId: 800000000006,
    personNumber: "IST-2205",
    displayName: "Synthetic Ground Operations IST-2205",
    department: "Ground Operations",
    jobTitle: "Ground Operations",
    assignmentStatus: "ACTIVE",
    dateOfBirthIso: "1988-08-27",
    biologicalSex: "male",
    dependents: []
  },
  {
    personId: 800000000007,
    personNumber: "IST-90001",
    displayName: "Synthetic Pilot IST-90001",
    department: "Flight Operations",
    jobTitle: "Pilot",
    assignmentStatus: "ACTIVE",
    dateOfBirthIso: "1990-12-09",
    biologicalSex: "male",
    dependents: []
  }
];

function addLegacyDemoWorkers(index: OracleIndex): void {
  for (const demo of LEGACY_DEMO_WORKERS) {
    index.publicWorkerByPersonNumber.set(demo.personNumber, {
      PersonId: demo.personId,
      PersonNumber: demo.personNumber,
      DisplayName: demo.displayName,
      WorkerType: "E",
      AssignmentNumber: `LEGACY-${demo.personNumber}`,
      AssignmentStatusType: demo.assignmentStatus,
      DepartmentName: demo.department,
      JobName: demo.jobTitle,
      LocationName: "Hamad International Airport",
      links: []
    });
    index.workerByPersonId.set(demo.personId, {
      workersUniqID: `LEGACY-WKR-${demo.personNumber}`,
      PersonId: demo.personId,
      PersonNumber: demo.personNumber,
      DisplayName: demo.displayName,
      DateOfBirth: demo.dateOfBirthIso,
      Gender: demo.biologicalSex === "female" ? "F" : "M",
      WorkerType: "E",
      CorrespondenceLanguage: "US",
      LegislationCode: "QA",
      links: []
    });
    index.assignmentByPersonId.set(demo.personId, {
      workersUniqID: `LEGACY-WKR-${demo.personNumber}`,
      PeriodOfServiceId: `LEGACY-POS-${demo.personNumber}`,
      AssignmentId: `LEGACY-ASG-${demo.personNumber}`,
      AssignmentNumber: `LEGACY-${demo.personNumber}`,
      PersonId: demo.personId,
      PersonNumber: demo.personNumber,
      AssignmentStatusType: demo.assignmentStatus,
      BusinessUnitName: "IST Tech Aviation Health Services",
      DepartmentName: demo.department,
      JobName: demo.jobTitle,
      LocationName: "Hamad International Airport",
      PrimaryAssignmentFlag: true,
      EffectiveStartDate: "2018-01-01"
    });

    const relationships: OracleContactRelationship[] = demo.dependents.map((dependent, position) => {
      const contactPersonId = demo.personId * 1000 + position + 1;
      index.contactsByContactPersonId.set(contactPersonId, {
        hcmContactsUniqID: `LEGACY-HCMC-${demo.personNumber}-${position + 1}`,
        ContactPersonId: contactPersonId,
        ContactPersonNumber: `LEGACY-DEP-${demo.personNumber}-${position + 1}`,
        DisplayName: `${demo.displayName} dependent ${position + 1}`,
        DateOfBirth: dependent.dateOfBirthIso,
        Gender: dependent.biologicalSex === "female" ? "F" : "M",
        LegislationCode: "QA",
        links: []
      });
      return {
        ContactRelationshipId: `LEGACY-HCMR-${demo.personNumber}-${position + 1}`,
        PersonId: demo.personId,
        PersonNumber: demo.personNumber,
        ContactPersonId: contactPersonId,
        ContactPersonNumber: `LEGACY-DEP-${demo.personNumber}-${position + 1}`,
        legacyDependentId: dependent.id,
        RelationshipType: dependent.relationshipType,
        EmergencyContactFlag: dependent.relationshipType === "SPOUSE",
        DependentFlag: true,
        StartDate: "2018-01-01"
      };
    });
    if (relationships.length > 0) {
      index.relationshipsByPersonId.set(demo.personId, relationships);
    }
  }
}

function buildIndex(): OracleIndex {
  const index: OracleIndex = {
    publicWorkerByPersonNumber: new Map(),
    workerByPersonId: new Map(),
    assignmentByPersonId: new Map(),
    absencesByPersonId: new Map(),
    contactsByContactPersonId: new Map(),
    relationshipsByPersonId: new Map()
  };

  if (existsSync(ORACLE_SEED_DATA_PATH)) {
    const seed = JSON.parse(readFileSync(ORACLE_SEED_DATA_PATH, "utf8")) as OracleSeedFile;
    const collections = seed.oracle_fusion_hcm_api.collections;

    for (const worker of collections.publicWorkers.items) {
      index.publicWorkerByPersonNumber.set(worker.PersonNumber, worker);
    }
    for (const worker of collections.workers.items) {
      index.workerByPersonId.set(worker.PersonId, worker);
    }
    for (const assignment of collections.assignments.items) {
      if (assignment.PrimaryAssignmentFlag) {
        index.assignmentByPersonId.set(assignment.PersonId, assignment);
      }
    }
    for (const absence of collections.absences.items) {
      const existing = index.absencesByPersonId.get(absence.PersonId) ?? [];
      existing.push(absence);
      index.absencesByPersonId.set(absence.PersonId, existing);
    }
    for (const contact of collections.hcmContacts.items) {
      index.contactsByContactPersonId.set(contact.ContactPersonId, contact);
    }
    for (const relationship of collections.contactRelationships.items) {
      const existing = index.relationshipsByPersonId.get(relationship.PersonId) ?? [];
      existing.push(relationship);
      index.relationshipsByPersonId.set(relationship.PersonId, existing);
    }
  }

  addLegacyDemoWorkers(index);
  return index;
}

function getIndex(): OracleIndex {
  if (!cachedIndex) {
    cachedIndex = buildIndex();
  }
  return cachedIndex;
}

/** Test-only: forces the index to be rebuilt on next access. */
export function resetOracleAdapterCacheForTests(): void {
  cachedIndex = undefined;
}

/**
 * Canonical mapping from Oracle's `AssignmentStatusType` (plus any active
 * approved absence) to IST's `dutyStatus` enum - see the "Canonical Mapping"
 * table in docs/oracle-fusion-hcm-integration.md.
 */
function dutyStatusFromOracle(assignmentStatusType: string, hasApprovedAbsence: boolean): StaffProfile["dutyStatus"] {
  if (assignmentStatusType === "INACTIVE") {
    return "inactive";
  }
  if (assignmentStatusType === "LEAVE_OF_ABSENCE" || hasApprovedAbsence) {
    return "on-leave";
  }
  return "active";
}

function relationshipTypeFromOracle(relationshipType: string): DependentProfile["relationshipType"] {
  if (relationshipType === "SPOUSE") return "spouse";
  if (relationshipType === "SON" || relationshipType === "DAUGHTER") return "child";
  if (relationshipType === "PARENT") return "parent";
  return "other";
}

function biologicalSexFromOracleGender(gender: string): "male" | "female" {
  return gender === "F" ? "female" : "male";
}

export function ageFromDateOfBirth(dateOfBirthIso: string): number {
  const dob = new Date(dateOfBirthIso);
  if (Number.isNaN(dob.getTime())) {
    return 0;
  }
  const now = new Date();
  let age = now.getUTCFullYear() - dob.getUTCFullYear();
  if (now.getUTCMonth() < dob.getUTCMonth() || (now.getUTCMonth() === dob.getUTCMonth() && now.getUTCDate() < dob.getUTCDate())) {
    age -= 1;
  }
  return Math.max(age, 0);
}

function dependentsForPerson(index: OracleIndex, personId: number): DependentProfile[] {
  const relationships = index.relationshipsByPersonId.get(personId) ?? [];
  const dependents: DependentProfile[] = [];
  for (const relationship of relationships) {
    const contact = index.contactsByContactPersonId.get(relationship.ContactPersonId);
    if (!contact) {
      continue;
    }
    dependents.push({
      id: relationship.legacyDependentId ?? `dep_${relationship.ContactRelationshipId.toLowerCase()}`,
      relationshipType: relationshipTypeFromOracle(relationship.RelationshipType),
      age: ageFromDateOfBirth(contact.DateOfBirth),
      dateOfBirthIso: contact.DateOfBirth,
      biologicalSex: biologicalSexFromOracleGender(contact.Gender)
    });
  }
  return dependents;
}

/**
 * Resolves a `StaffProfile` for a given IST staff ID (Oracle `PersonNumber`),
 * implementing the exact runtime flow documented in
 * docs/oracle-fusion-hcm-integration.md: publicWorkers lookup -> assignment
 * for department/job/duty context -> absences for leave context ->
 * hcmContacts/contactRelationships for dependents -> normalize into the
 * stable IST `StaffProfile` shape. Returns undefined if the person number
 * isn't found, matching the "worker does not exist" case a real Oracle
 * adapter would also need to handle.
 */
export function resolveStaffProfile(istStaffId: string): StaffProfile | undefined {
  const index = getIndex();
  const worker = index.publicWorkerByPersonNumber.get(istStaffId.toUpperCase());
  if (!worker) {
    return undefined;
  }

  const assignment = index.assignmentByPersonId.get(worker.PersonId);
  const workerDetail = index.workerByPersonId.get(worker.PersonId);
  const absences = index.absencesByPersonId.get(worker.PersonId) ?? [];
  const hasApprovedAbsence = absences.some((absence) => absence.ApprovalStatusCd === "APPROVED");
  const assignmentStatusType = assignment?.AssignmentStatusType ?? worker.AssignmentStatusType;

  return {
    id: `oracle_person_${worker.PersonId}`,
    istStaffId: worker.PersonNumber,
    department: assignment?.DepartmentName ?? worker.DepartmentName,
    jobTitle: assignment?.JobName ?? worker.JobName,
    dutyStatus: dutyStatusFromOracle(assignmentStatusType, hasApprovedAbsence),
    dateOfBirthIso: workerDetail?.DateOfBirth,
    biologicalSex: workerDetail?.Gender ? biologicalSexFromOracleGender(workerDetail.Gender) : undefined,
    insuranceProvider: "IST Staff Health Plan",
    insuranceEligibilityStatus: "eligible",
    insuranceLastChecked: "2026-07-01T08:00:00.000Z",
    dependents: dependentsForPerson(index, worker.PersonId)
  };
}

/** Resolves either an employee number or a globally unique dependent ID. */
export function resolvePatientIdentifier(patientIdentifier: string):
  | { profile: StaffProfile; dependent?: DependentProfile }
  | undefined {
  const normalized = patientIdentifier.trim();
  if (!normalized) return undefined;

  const staff = resolveStaffProfile(normalized);
  if (staff) return { profile: staff };

  const index = getIndex();
  for (const worker of index.publicWorkerByPersonNumber.values()) {
    const profile = resolveStaffProfile(worker.PersonNumber);
    const dependent = profile?.dependents.find(
      (candidate) => candidate.id.toUpperCase() === normalized.toUpperCase()
    );
    if (profile && dependent) return { profile, dependent };
  }
  return undefined;
}
