import { existsSync, readFileSync } from "node:fs";
import path from "node:path";
import type { StaffProfile, StaffValidationResult } from "../types/triage.js";

const SYNTHETIC_STAFF_POOL_PATH = path.resolve(process.cwd(), "data", "mock-hrms-staff-pool.json");

/**
 * Loads a large (1000-profile) synthetic staff pool for testing scenarios that
 * need many distinct employees - e.g. an end-to-end corpus-wide verification
 * sweep across all protocols, where reusing a handful of staff IDs repeatedly
 * would accumulate call history and bias protocol-matching results (see the
 * `batch-verification-process` memory for the documented staff-ID contamination
 * artifact). Generated by a one-off script, not hand-authored - safe to
 * regenerate at any size. Returns an empty object if the file is missing so
 * this stays optional/non-breaking for environments that don't need it.
 */
function loadSyntheticStaffPool(): Record<string, StaffProfile> {
  if (!existsSync(SYNTHETIC_STAFF_POOL_PATH)) {
    return {};
  }
  try {
    return JSON.parse(readFileSync(SYNTHETIC_STAFF_POOL_PATH, "utf8")) as Record<string, StaffProfile>;
  } catch {
    return {};
  }
}

export type PatientAgeResolution =
  | {
      ok: true;
      source: "staff" | "dependent";
      ageYears: number;
      ageMonths: number;
      dateOfBirthIso?: string;
      calculatedFrom: "HRMS_DATE_OF_BIRTH" | "HRMS_AGE_FIELD";
    }
  | { ok: false; status: 400 | 404; reason: string };

// Mock directory adapter. The production target is an Oracle Fusion HCM adapter;
// keep this response shape stable for the triage API.
const staffDirectory: Record<string, StaffProfile> = {
  "IST-1001": {
    id: "staff_ist_1001",
    istStaffId: "IST-1001",
    department: "Flight Operations",
    jobTitle: "Pilot",
    dutyStatus: "active",
    dateOfBirthIso: "1991-03-15",
    insuranceProvider: "IST Staff Health Plan",
    insuranceEligibilityStatus: "eligible",
    insuranceLastChecked: "2026-07-01T08:00:00.000Z",
    dependents: [
      {
        id: "dep_ist_1001_child_01",
        relationshipType: "child",
        age: 6,
        dateOfBirthIso: "2020-04-02",
        biologicalSex: "female"
      },
      {
        id: "dep_ist_1001_child_02",
        relationshipType: "child",
        age: 3,
        dateOfBirthIso: "2023-02-12",
        biologicalSex: "male"
      }
    ]
  },
  "IST-10001": {
    id: "staff_demo_10001",
    istStaffId: "IST-10001",
    department: "Flight Operations",
    jobTitle: "Cabin Crew",
    dutyStatus: "active",
    dateOfBirthIso: "1994-05-20",
    insuranceProvider: "IST Staff Health Plan",
    insuranceEligibilityStatus: "eligible",
    insuranceLastChecked: "2026-07-01T08:00:00.000Z",
    dependents: [
      {
        id: "dep_demo_10001_child",
        relationshipType: "child",
        age: 8,
        dateOfBirthIso: "2018-01-10",
        biologicalSex: "female"
      }
    ]
  },
  "IST-2002": {
    id: "staff_ist_2002",
    istStaffId: "IST-2002",
    department: "Cabin Services",
    jobTitle: "Cabin Crew",
    dutyStatus: "active",
    dateOfBirthIso: "1985-09-08",
    insuranceProvider: "IST Staff Health Plan",
    insuranceEligibilityStatus: "eligible",
    insuranceLastChecked: "2026-07-01T08:00:00.000Z",
    dependents: []
  },
  "IST-20002": {
    id: "staff_demo_20002",
    istStaffId: "IST-20002",
    department: "Ground Services",
    jobTitle: "Ramp Supervisor",
    dutyStatus: "on-leave",
    dateOfBirthIso: "1979-11-18",
    insuranceProvider: "IST Staff Health Plan",
    insuranceEligibilityStatus: "pending-verification",
    insuranceLastChecked: "2026-06-20T08:00:00.000Z",
    dependents: []
  },
  "IST-3003": {
    id: "staff_ist_3003",
    istStaffId: "IST-3003",
    department: "Airport Operations",
    jobTitle: "Operations Specialist",
    dutyStatus: "active",
    dateOfBirthIso: "1997-06-21",
    insuranceProvider: "IST Staff Health Plan",
    insuranceEligibilityStatus: "eligible",
    insuranceLastChecked: "2026-07-01T08:00:00.000Z",
    dependents: []
  },
  "IST-2205": {
    id: "staff_ist_2205",
    istStaffId: "IST-2205",
    department: "Ground Operations",
    jobTitle: "Ground Operations",
    dutyStatus: "active",
    dateOfBirthIso: "1988-08-27",
    insuranceProvider: "IST Staff Health Plan",
    insuranceEligibilityStatus: "eligible",
    insuranceLastChecked: "2026-07-01T08:00:00.000Z",
    dependents: []
  },
  "IST-90001": {
    id: "staff_ist_90001",
    istStaffId: "IST-90001",
    department: "Flight Operations",
    jobTitle: "Pilot",
    dutyStatus: "active",
    dateOfBirthIso: "1990-12-09",
    insuranceProvider: "IST Staff Health Plan",
    insuranceEligibilityStatus: "eligible",
    insuranceLastChecked: "2026-07-01T08:00:00.000Z",
    dependents: []
  },
  ...loadSyntheticStaffPool()
};

export function getStaffProfileFromDirectory(istStaffId: string): StaffProfile | undefined {
  return staffDirectory[istStaffId.toUpperCase()];
}

export async function validateStaffMember(istStaffId: string): Promise<StaffValidationResult> {
  const profile = getStaffProfileFromDirectory(istStaffId);
  if (!profile) {
    return {
      valid: false,
      reason: "IST staff ID was not found in the mock HRMS directory."
    };
  }

  if (profile.dutyStatus === "inactive" || profile.dutyStatus === "suspended") {
    return {
      valid: false,
      profile,
      reason: `Staff duty status is ${profile.dutyStatus}; manual verification is required.`
    };
  }

  return { valid: true, profile };
}

export function findDependent(profile: StaffProfile, dependentId?: string) {
  if (!dependentId) {
    return undefined;
  }

  return profile.dependents.find((dependent) => dependent.id === dependentId);
}

export function calculateAgeFromDateOfBirth(dateOfBirthIso: string, referenceDate = new Date()): {
  ageYears: number;
  ageMonths: number;
} {
  const dateOfBirth = new Date(dateOfBirthIso);
  if (Number.isNaN(dateOfBirth.getTime()) || dateOfBirth > referenceDate) {
    throw new Error("Invalid HRMS date of birth.");
  }

  let ageMonths =
    (referenceDate.getUTCFullYear() - dateOfBirth.getUTCFullYear()) * 12 +
    (referenceDate.getUTCMonth() - dateOfBirth.getUTCMonth());

  if (referenceDate.getUTCDate() < dateOfBirth.getUTCDate()) {
    ageMonths -= 1;
  }

  return {
    ageYears: Math.floor(Math.max(ageMonths, 0) / 12),
    ageMonths: Math.max(ageMonths, 0)
  };
}

export function resolvePatientAgeFromDirectory(args: {
  istStaffId: string;
  dependentId?: string;
  referenceDate?: Date;
}): PatientAgeResolution {
  const profile = getStaffProfileFromDirectory(args.istStaffId);
  if (!profile) {
    return {
      ok: false,
      status: 404,
      reason: "Staff member was not found in HRMS."
    };
  }

  if (profile.dutyStatus === "inactive" || profile.dutyStatus === "suspended") {
    return {
      ok: false,
      status: 400,
      reason: `Staff duty status is ${profile.dutyStatus}; manual verification is required.`
    };
  }

  const dependent = findDependent(profile, args.dependentId);
  if (args.dependentId && !dependent) {
    return {
      ok: false,
      status: 400,
      reason: "Dependent is not mapped to the validated staff member."
    };
  }

  const source = dependent ? "dependent" : "staff";
  const dateOfBirthIso = dependent?.dateOfBirthIso ?? profile.dateOfBirthIso;
  if (dateOfBirthIso) {
    return {
      ok: true,
      source,
      dateOfBirthIso,
      calculatedFrom: "HRMS_DATE_OF_BIRTH",
      ...calculateAgeFromDateOfBirth(dateOfBirthIso, args.referenceDate)
    };
  }

  if (dependent) {
    return {
      ok: true,
      source,
      ageYears: dependent.age,
      ageMonths: dependent.age * 12,
      calculatedFrom: "HRMS_AGE_FIELD"
    };
  }

  return {
    ok: false,
    status: 400,
    reason: "HRMS did not return date of birth for the selected staff member."
  };
}

export async function resolvePatientAgeFromHrms(args: {
  istStaffId: string;
  dependentId?: string;
  referenceDate?: Date;
}): Promise<PatientAgeResolution> {
  return resolvePatientAgeFromDirectory(args);
}
