export type RemediationDocumentationItem = {
  id: `PR-${string}`;
  owner: string;
  technicalStatus: string;
  evidence: string;
  approvalRequired: string;
};

/** Canonical, reconciled PR-001 through PR-015 application documentation. */
export const REMEDIATION_APPROVAL_ITEMS: readonly RemediationDocumentationItem[] = [
  { id: "PR-001", owner: "Engineering + IAM", technicalStatus: "Complete with explicit demo-only exception", evidence: "Seeded credentials fail closed by default in production. SOC2 uses governed credentials and MFA; synthetic demo testing alone explicitly enables demo credentials and disables mandatory MFA.", approvalRequired: "Closed. The demo exception must never be copied to SOC2 or a live-data environment." },
  { id: "PR-002", owner: "DevOps", technicalStatus: "Complete", evidence: "Clean-tree release controls map the approved Git SHA through Cloud Build and immutable image digest to Cloud Run revision labels and the live runtime response.", approvalRequired: "Closed. Each future release must preserve the same provenance chain." },
  { id: "PR-003", owner: "DevOps + Security", technicalStatus: "Complete", evidence: "All eight required persistence flags, current migrations, and cross-revision MFA, session, queue, audit, reveal, and anomaly-state durability were verified.", approvalRequired: "Closed. Persistence flags and migrations remain deployment gates." },
  { id: "PR-004", owner: "Engineering + Security", technicalStatus: "Complete", evidence: "Assignment-time segregation-of-duties validation and SOC2 administrator PAM UAT reject conflicting role assignment and permission grants with HTTP 409; controlled records were cleaned.", approvalRequired: "Closed. Custom roles remain subject to elevated, audited conflict validation." },
  { id: "PR-005", owner: "Product + Security", technicalStatus: "Complete", evidence: "The protected catalog contains exactly Triage Nurse, Triage Service Manager, and Platform Administrator. A Platform Administrator can create governed custom roles.", approvalRequired: "Closed. Historical larger-role catalogs are not the current authorization model." },
  { id: "PR-006", owner: "Clinical QA", technicalStatus: "SOC2 technical verification complete; clinical sign-off and promotion pending", evidence: "The five-protocol SOC2 regression passed 30/30 governed cases plus three fail-closed negatives. Advice follows the selected protocol and exact TAQ question to its disposition and authored advice.", approvalRequired: "Clinical QA must approve protocol wording, TAQ-to-disposition mapping, and care-advice content." },
  { id: "PR-007", owner: "Engineering", technicalStatus: "Complete", evidence: "Governed SOC2 nurse UAT verified incremental IAQ, TAQ, and approval merges, hold/resume reload, disposition locking, idempotent retry, late-answer rejection, storage integrity, and audited cleanup.", approvalRequired: "Closed. Clinical JSON updates must continue through the backend merge invariant." },
  { id: "PR-008", owner: "Cloud owner", technicalStatus: "Risk accepted - temporary remediation topology", evidence: "Demo and SOC2 use separate databases, users, and secrets on one Cloud SQL instance. SOC2 is the remediation authority during customer security validation.", approvalRequired: "An approved final consolidation must decommission SOC2 and record retained evidence and deletion verification." },
  { id: "PR-009", owner: "Cloud Security", technicalStatus: "Complete", evidence: "Demo and SOC2 services and the six SOC2 jobs use the dedicated keyless runtime identity with per-secret access scoped and live inventory reverified.", approvalRequired: "Closed. Any surviving or new workload must retain a dedicated least-privilege identity." },
  { id: "PR-010", owner: "Security Architecture", technicalStatus: "Technical remediation complete on SOC2; architecture approval pending", evidence: "SOC2 uses an insert/select-only audit login, HMAC event chaining, authenticated integrity verification, mutation denial, and an explicit boundary for 2,376 legacy unsigned rows.", approvalRequired: "Security Architecture must accept ledger design, key custody and rotation, database-role boundary, legacy treatment, and immutable-export roadmap." },
  { id: "PR-011", owner: "Privacy + Legal + Engineering", technicalStatus: "Technical activation complete; recurring execute approval pending", evidence: "The retention period is 365 days. Archive precedes deletion, legal holds override deletion, concurrent execution is serialized, the live hold-first race retained the record, and the scheduler remains dry-run.", approvalRequired: "Privacy and Legal must approve recurring destructive execution before the scheduler receives execute mode." },
  { id: "PR-012", owner: "DevOps", technicalStatus: "Complete", evidence: "Healthy triage and aimltriage.com marketing certificate chains were documented, stale load-balancer resources were removed, and DNS, TLS, and HTTP validation passed.", approvalRequired: "Closed. Certificate ownership and renewal health remain monitored controls." },
  { id: "PR-013", owner: "QA + DevOps", technicalStatus: "Complete", evidence: "CI uses an isolated PostgreSQL 15 service, a fail-closed database guard, migrations, and the complete green Jest database-backed run.", approvalRequired: "Closed. Technical test completion does not substitute for clinical UAT." },
  { id: "PR-014", owner: "QA + Security", technicalStatus: "Complete", evidence: "SOC2 exact-HTTP UAT passed administrator, manager, and nurse boundaries; PAM elevation; create, duplicate, invalid, and conflict cases; reversible permission grant; audit lookup; and approved cleanup.", approvalRequired: "Closed. Future releases retain this administrator boundary matrix." },
  { id: "PR-015", owner: "Clinical QA", technicalStatus: "Technical deployment matrix passed; clinical signature pending", evidence: "The deployed five-protocol matrix passed 25/25 ambiguity/no-match cases and 100/100 clinical regressions, with nurse-override evidence for AMBIGUOUS and NO_MATCH results.", approvalRequired: "Clinical QA must sign the matching thresholds, examples, and nurse-override behavior." }
];
